#!/bin/bash
# Author: @FershoUno
# License: GPLv3

# List of Packages from RPM
LIST_PACKAGES=()

# VARIABLES
PATH_PACKAGES="Fedora-Packages"
NAME_TAR="Fedora-Packages"

# Gets the installed Fedora version
VERSION_FEDORA="-$(cat /etc/os-release | grep -i VERSION_ID | cut -d "=" -f 2)"
echo -e "\n Fedora Version: $VERSION_FEDORA \n"

for i in "${LIST_PACKAGES[@]}"; do
    echo -e "\n Preparing package $i \n"
    mkdir -p $PATH_PACKAGES$VERSION_FEDORA/$i-packages
    dnf download --resolve --destdir=$PATH_PACKAGES$VERSION_FEDORA/$i-packages $i -y
    echo -e "\n Package $i downloaded \n"
done

# Installer script generator
echo "#!/bin/bash
# Author: @FershoUno
# License: GPLv3

# RPM Package installer
LIST_PACKAGES_RPM=("${LIST_PACKAGES[@]}")

for i in \"\${LIST_PACKAGES_RPM[@]}\"
do
    echo -e \"\n Installing Package \$i \n\"
    dnf install --nogpgcheck --disablerepo=* ./\$i-packages/* -y
    echo -e \"\n \$i installation completed \n\"
done
" > $PATH_PACKAGES$VERSION_FEDORA/installer

# Compress Fedora-Packages with tar.gz
echo "Creating compression $NAME_TAR$VERSION_FEDORA.tar.gz"
tar -czvf $NAME_TAR$VERSION_FEDORA.tar.gz $PATH_PACKAGES$VERSION_FEDORA/

echo -e "\n $NAME_TAR$VERSION_FEDORA.tar.gz created, finishing! \n"
