#!/bin/bash
# Author: @FershoUno
# License: GPLv3

# Lista de Paquetes desde RPM
LIST_PACKAGES=()

# VARIABLES
PATH_PACKAGES="Fedora-Packages"
NAME_TAR="Fedora-Packages"

# Obtiene la versión de Fedora que esta instalado
VERSION_FEDORA="-$(cat /etc/os-release | grep -i VERSION_ID | cut -d "=" -f 2)"
echo -e "\n Version de Fedora: $VERSION_FEDORA \n"

for i in "${LIST_PACKAGES[@]}"; do
    echo -e "\n Preparando el paquete $i \n"
    mkdir -p $PATH_PACKAGES$VERSION_FEDORA/$i-packages
    dnf download --resolve --destdir=$PATH_PACKAGES$VERSION_FEDORA/$i-packages $i -y
    echo -e "\n Paquete $i Descargado \n"
done

# Generador de script installer
echo "#!/bin/bash
# Author: @FershoUno
# License: GPLv3

# Instalador de paquetes RPM
LIST_PACKAGES_RPM=("${LIST_PACKAGES[@]}")

for i in \"\${LIST_PACKAGES_RPM[@]}\"
do
    echo -e \"\n Instalando Paquete \$i \n\"
    dnf install --nogpgcheck --disablerepo=* ./\$i-packages/* -y
    echo -e \"\n Se terminó de instalar \$i \n\"
done
" > $PATH_PACKAGES$VERSION_FEDORA/installer


#Comprimir Fedora-Packages con tar.gz
echo "Creando compresión $NAME_TAR$VERSION_FEDORA.tar.gz"
tar -czvf $NAME_TAR$VERSION_FEDORA.tar.gz $PATH_PACKAGES$VERSION_FEDORA/

echo -e "\n Se creo $NAME_TAR$VERSION_FEDORA.tar.gz, finalizando! \n"
